server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437